on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://ssh.strato.de:22/
        ftp-username: sftp_gewaesserinfo@schattenfell.net
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure
